Added echo of error and exit if failed

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -51,18 +51,16 @@ jobs:
               "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ steps.login-aws-ecr.outputs.registry }}",
             ]' --query "Command.CommandId" --output text)
 
-            echo "$command_id"
-
             aws ssm wait command-executed \
             --command-id $command_id \
             --instance-id i-02e66248b0e330fae
 
             status=$(aws ssm list-commands --command-id $command_id --query "Commands[0].StatusDetails" --output text)
 
-            echo "$status"
-
             if [ $status == "Success" ]; then
               echo "Command executed successfully"
             else
               echo "Command failed"
+              echo "Error: $status"
+              exit 1
             fi
